const assert = require('assert')
const fs = require('fs')
const path = require('path')
const { COMPANIONS, getAvatarName, getCompanionGreeting } = require('../utils/universe')

assert.strictEqual(COMPANIONS.length, 3)
assert.strictEqual(getAvatarName(0), '光年旅人')
assert.strictEqual(getAvatarName(4), '光年旅人')
assert.strictEqual(getCompanionGreeting('curious'), '前面有一颗新星，要一起去看看吗？')
assert.strictEqual(getCompanionGreeting('unknown'), '我在这里，陪你慢慢探索。')

const pageSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.js'), 'utf8')
const templateSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.wxml'), 'utf8')
const componentSource = fs.readFileSync(path.join(__dirname, '../components/xr-companion/index.js'), 'utf8')
const pageConfigSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.json'), 'utf8')
const styleSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.wxss'), 'utf8')

assert.ok(pageSource.includes("scope: 'scope.camera'"))
assert.ok(pageSource.includes('wx.chooseMedia'))
assert.ok(pageSource.includes('avatarVersion'))
assert.ok(pageSource.includes('immersiveMode'))
assert.ok(pageSource.includes('immersiveMode: true'))
assert.ok(pageSource.includes('avatarVersion: saved.version || Date.now(),\n        immersiveMode: false'))
assert.ok(pageSource.includes('sceneWidth'))
assert.ok(pageSource.includes('sceneHeight'))
assert.ok(pageSource.includes('renderWidth'))
assert.ok(pageSource.includes('renderHeight'))
assert.ok(pageSource.includes('pixelRatio'))
assert.ok(pageSource.includes('controlTop'))
assert.ok(pageSource.includes('getMenuButtonBoundingClientRect'))
assert.ok(pageSource.includes('wx.hideTabBar'))
assert.ok(pageSource.includes('wx.showTabBar'))
assert.ok(templateSource.includes('avatar-path="{{avatarPath}}"'))
assert.ok(templateSource.includes('avatar-version="{{avatarVersion}}"'))
assert.ok(templateSource.includes('width="{{renderWidth}}"'))
assert.ok(templateSource.includes('height="{{renderHeight}}"'))
assert.ok(templateSource.includes('style="width:{{sceneWidth}}px;height:{{sceneHeight}}px;display:block;"'))
assert.ok(templateSource.includes("immersiveMode ? 'immersive-page' : ''"))
assert.ok(templateSource.includes('<view wx:if="{{immersiveMode && !cameraOpen}}" class="immersive-close"'))
assert.ok(templateSource.includes('catchtap="exitImmersive">退出全屏</view>'))
assert.ok(templateSource.includes('<view wx:if="{{cameraOpen}}" class="ar-close"'))
assert.ok(templateSource.includes('catchtap="closeCamera">退出 AR</view>'))
assert.ok(templateSource.includes('style="top:{{controlTop}}px;"'))
assert.ok(templateSource.includes('class="xr-ui-layer"'))
assert.ok(templateSource.includes('class="ar-loading-camera"'))
assert.ok(styleSource.includes('position: fixed'))
assert.ok(styleSource.includes('bottom: 0'))
assert.ok(styleSource.includes('.ar-loading-camera'))
assert.ok(pageConfigSource.includes('navigationStyle'))
assert.ok(pageConfigSource.includes('"navigationStyle": "custom"'))
assert.ok(componentSource.includes('loadAvatarTexture'))
assert.ok(componentSource.includes("setTexture('u_baseColorMap'"))
assert.ok(componentSource.includes('handleTick'))
assert.ok(componentSource.includes('rotation.y'))
assert.ok(pageConfigSource.includes('xr-ar-companion'))
assert.ok(templateSource.includes('xr-ar-companion'))
assert.ok(templateSource.includes('immersive-stage'))
assert.ok(templateSource.includes('wx:if="{{!immersiveMode}}" class="create-card"'))
assert.ok(styleSource.includes('.xr-stage xr-ar-companion'))
assert.ok(pageSource.includes("sourceType: ['camera']"))
const arComponentSource = fs.readFileSync(path.join(__dirname, '../components/xr-ar-companion/index.wxml'), 'utf8')
const arStyleSource = fs.readFileSync(path.join(__dirname, '../components/xr-ar-companion/index.wxss'), 'utf8')
const companionStyleSource = fs.readFileSync(path.join(__dirname, '../components/xr-companion/index.wxss'), 'utf8')
assert.ok(arComponentSource.includes('ar-system='))
assert.ok(arComponentSource.includes('xr-ar-tracker'))
assert.ok(arComponentSource.includes('background="ar"'))
assert.ok(arStyleSource.includes('position: absolute'))
assert.ok(arStyleSource.includes('canvas'))
assert.ok(companionStyleSource.includes('position: absolute'))

console.log('universe tests passed')
