const assert = require('assert')
const fs = require('fs')
const path = require('path')
const { COMPANIONS, getAvatarName, getCompanionGreeting } = require('../utils/universe')

assert.strictEqual(COMPANIONS.length, 3)
assert.strictEqual(getAvatarName(0), '光年旅人')
assert.strictEqual(getAvatarName(4), '光年旅人')
assert.strictEqual(getCompanionGreeting('curious'), '前面有一颗新星，要一起去看看吗？')
assert.strictEqual(getCompanionGreeting('unknown'), '我在这里，陪你慢慢探索。')

const pageSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.js'), 'utf8')
const templateSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.wxml'), 'utf8')
const componentSource = fs.readFileSync(path.join(__dirname, '../components/xr-companion/index.js'), 'utf8')
const pageConfigSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.json'), 'utf8')
const styleSource = fs.readFileSync(path.join(__dirname, '../pages/universe/index.wxss'), 'utf8')

assert.ok(pageSource.includes("scope: 'scope.camera'"))
assert.ok(pageSource.includes('wx.chooseMedia'))
assert.ok(pageSource.includes('avatarVersion'))
assert.ok(pageSource.includes('immersiveMode'))
assert.ok(pageSource.includes('immersiveMode: true'))
assert.ok(templateSource.includes('avatar-path="{{avatarPath}}"'))
assert.ok(templateSource.includes('avatar-version="{{avatarVersion}}"'))
assert.ok(templateSource.includes("immersiveMode ? 'immersive-page' : ''"))
assert.ok(templateSource.includes('wx:if="{{immersiveMode}}" class="immersive-close"'))
assert.ok(templateSource.includes('class="xr-ui-layer"'))
assert.ok(templateSource.includes('class="ar-loading-camera"'))
assert.ok(styleSource.includes('position: fixed'))
assert.ok(styleSource.includes('.ar-loading-camera'))
assert.ok(pageConfigSource.includes('navigationStyle'))
assert.ok(pageConfigSource.includes('"navigationStyle": "custom"'))
assert.ok(componentSource.includes('loadAvatarTexture'))
assert.ok(componentSource.includes("setTexture('u_baseColorMap'"))
assert.ok(componentSource.includes('handleTick'))
assert.ok(componentSource.includes('rotation.y'))
assert.ok(pageConfigSource.includes('xr-ar-companion'))
assert.ok(templateSource.includes('xr-ar-companion'))
assert.ok(templateSource.includes('immersive-stage'))
assert.ok(templateSource.includes('wx:if="{{!immersiveMode}}" class="create-card"'))
assert.ok(styleSource.includes('.xr-stage xr-ar-companion'))
assert.ok(pageSource.includes("sourceType: ['camera']"))
const arComponentSource = fs.readFileSync(path.join(__dirname, '../components/xr-ar-companion/index.wxml'), 'utf8')
assert.ok(arComponentSource.includes('ar-system='))
assert.ok(arComponentSource.includes('xr-ar-tracker'))
assert.ok(arComponentSource.includes('background="ar"'))

console.log('universe tests passed')
